import './globals.css'
import { Inter as FontSans } from "next/font/google"
 
const fontSans = FontSans({
  subsets: ["latin"],
})

export const metadata = {
  title: 'Next.js + App router',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={fontSans.className}>{children}</body>
    </html>
  )
}
